name: Publish on NPM
permissions:
  id-token: write
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: |
          npm ci
      - name: Test Node.js
        run: |
          npm test
      - name: Publish to npm
        run: |
          cd ${GITHUB_WORKSPACE}
          npm publish --provenance --access public --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
